//
//  DashboardVideModel.swift
//  KataKanji
//
//  Created by Aldino Efendi on 2022/05/01.
//

import Foundation

class DashboardViewModel: ObservableObject {
	
	@Published var userData: UserModel? = nil
	@Published var article: [ArticleModel] = []

	init() {
		getData()
	}
	
	
	func getData() {
		let newModel = UserModel(
			level: Level.Pemula.rawValue,
			articleReaded: 4,
			quizDone: 4,
			listArticle: 15,
			listQuiz: 15,
			progress: 0.3
		)
		userData = newModel

		let newArticles = [
			ArticleModel(
				image: "trophy",
				titleJP: "ダルビッシュが沢村賞選考にもの申す「今の時代にあった評価してあげるべき」",
				titleID: "Darvish berkata kepada pemilihan Penghargaan Sawamura \"Saya harus mengevaluasinya sesuai dengan era sekarang\"",
				level: "Pemula",
				topic: "Olahraga",
				articleJP: "パドレスのダルビッシュ有投手（35）が22日（日本時間23日）、沢村賞の選考にもの申した。22日に発表された沢村賞は、オリックス山本由伸投手（23）が満場一致で選出され、他の投手からライバルが出ない状況に選考委員から「レベルが低すぎる」と苦言が出たことを受け、自身のツイッターで意見を投稿。「時代が変わってきている分、起用法も変わりますから数字も変わりますよね。今の時代にあった評価をしてあげるべきでは？」と考えを述べた。この意見はファンの間で大きな反響を呼び、賛否両論の多数のコメントが寄せられた。",
				articleID: "Yu Darvish dari Padres (35) mengajukan permohonan Penghargaan Sawamura pada tanggal 22 (23 waktu Jepang). Dalam Penghargaan Sawamura yang diumumkan pada tanggal 22, pelempar Yoshinobu Yamamoto (23) terpilih dengan suara bulat, dan panitia seleksi mengeluh bahwa levelnya terlalu rendah ketika tidak ada saingan dari pelempar lain. Terima dan posting pendapat Anda di Twitter Anda sendiri. \"Seiring waktu berubah, penggunaannya akan berubah, jadi jumlahnya akan berubah. Haruskah kita memberikan evaluasi yang sesuai dengan waktu?\" Pendapat ini menjadi hit besar di kalangan penggemar, dengan banyak komentar pro dan kontra.",
				articleSource: "https://news.yahoo.co.jp/articles/e60cf9fb883236bb93316b7ea9296d1f3d3a2d5b",
				isSeen: false,
				isQuizTaken: false,
				kanji: [
					KanjiModel(kanji: "沢", kunyomi: "さわ", onyomi: "タク", meaning: "Kecemerlangan", level: "Mahir"),
					KanjiModel(kanji: "村", kunyomi: "むら", onyomi: "ソン", meaning: "Desa, Kota", level: "Mahir"),
					KanjiModel(kanji: "賞", kunyomi: "ほ.める", onyomi: "ショウ", meaning: "hadiah, penghargaan, pujian", level: "Mahir"),
					KanjiModel(kanji: "選", kunyomi: "えら.ぶ", onyomi: "セン", meaning: "memilih", level: "Lanjut"),
					KanjiModel(kanji: "考", kunyomi: "かんが.える", onyomi: "コウ", meaning: "pertimbangkan, pikirkan", level: "Pemula"),
					KanjiModel(kanji: "申", kunyomi: "もう.す", onyomi: "シン", meaning: "monyet", level: "Lanjut"),
					KanjiModel(kanji: "今", kunyomi: "いま", onyomi: "コン、 キン", meaning: "sekarang", level: "Pemula"),
					KanjiModel(kanji: "時", kunyomi: "とき、 どき", onyomi: "ジ", meaning: "waktu, jam", level: "Pemula"),
					KanjiModel(kanji: "代", kunyomi: "か.わる", onyomi: "ダイ、 タイ", meaning: "mengganti, mengubah, mengonversi", level: "Pemula"),
					KanjiModel(kanji: "評", kunyomi: "-", onyomi: "ヒョウ", meaning: "evaluasi, kritik, komentar", level: "Mahir"),
					KanjiModel(kanji: "価", kunyomi: "あたい", onyomi: "カ、 ケ", meaning: "value, price", level: "Mahir"),
					KanjiModel(kanji: "有", kunyomi: "あ.る", onyomi: "ユウ、 ウ", meaning: "nilai, memiliki", level: "Pemula"),
					KanjiModel(kanji: "投", kunyomi: "な.げる、 な.げ", onyomi: "トウ", meaning: "lempar, buang, tinggalkan", level: "Lanjut"),
					KanjiModel(kanji: "手", kunyomi: "て", onyomi: "シュ、 ズ", meaning: "tangan", level: "Pemula"),
					KanjiModel(kanji: "日", kunyomi: "ひ、 び、 か", onyomi: "ニチ、 ジツ", meaning: "hari, matahari", level: "Pemula"),
					KanjiModel(kanji: "本", kunyomi: "もと", onyomi: "ホン", meaning: "buku, sekarang", level: "Pemula"),
					KanjiModel(kanji: "間", kunyomi: "あいだ、 ま、 あい", onyomi: "カン、 ケン", meaning: "interval, spasi", level: "Pemula"),
					KanjiModel(kanji: "発", kunyomi: "た.つ、 あば.く", onyomi: "ハツ、 ホツ", meaning: "keberangkatan, pelepasan", level: "Pemula"),
					KanjiModel(kanji: "表", kunyomi: "おもて", onyomi: "ヒョウ", meaning: "permukaan, tabel", level: "Lanjut"),
					KanjiModel(kanji: "山", kunyomi: "やま", onyomi: "サン、 セン", meaning: "gunung", level: "Pemula"),
					KanjiModel(kanji: "由", kunyomi: "よし、 よ.る", onyomi: "ユ、 ユウ、 ユイ", meaning: "oleh karena itu, alasan", level: "Lanjut"),
					KanjiModel(kanji: "伸", kunyomi: "の.びる、 の.ばす", onyomi: "シン", meaning: "memperluas, meregangkan", level: "Mahir"),
					KanjiModel(kanji: "満", kunyomi: "み.ちる", onyomi: "マン、 バン", meaning: "penuh, kepenuhan,", level: "Lanjut"),
					KanjiModel(kanji: "場", kunyomi: "ば", onyomi: "ジョウ、 チョウ", meaning: "lokasi, tempat", level: "Pemula"),
					KanjiModel(kanji: "致", kunyomi: "いた.す", onyomi: "チ", meaning: "melakukan, melakukan", level: "Mahir"),
					KanjiModel(kanji: "出", kunyomi: "で.る、 で", onyomi: "シュツ、 スイ", meaning: "keluar, menonjol", level: "Pemula"),
					KanjiModel(kanji: "他", kunyomi: "ほか", onyomi: "タ", meaning: "lain, yang lain", level: "Lanjut"),
					KanjiModel(kanji: "状", kunyomi: "-", onyomi: "ジョウ", meaning: "status quo, kondisi", level: "Lanjut"),
					KanjiModel(kanji: "況", kunyomi: "まし.て", onyomi: "キョウ", meaning: "kondisi, situasi", level: "Mahir"),
					KanjiModel(kanji: "委", kunyomi: "ゆだ.ねる", onyomi: "イ", meaning: "komite, mempercayakan", level: "Mahir"),
					KanjiModel(kanji: "員", kunyomi: "-", onyomi: "イン", meaning: "karyawan, anggota", level: "Pemula"),
					KanjiModel(kanji: "低", kunyomi: "ひく.い、 ひく.める", onyomi: "テイ", meaning: "lebih rendah, pendek", level: "Mahir"),
					KanjiModel(kanji: "苦", kunyomi: "くる.しい", onyomi: "ク", meaning: "penderitaan, cobaan", level: "Lanjut"),
					KanjiModel(kanji: "言", kunyomi: "い.う、 こと", onyomi: "ゲン、 ゴン", meaning: "katakan sesuatu", level: "Pemula"),
					KanjiModel(kanji: "受", kunyomi: "う.ける", onyomi: "ジュ", meaning: "menerima, menjalani", level: "Lanjut"),
					KanjiModel(kanji: "自", kunyomi: "みずか.ら", onyomi: "ジ、 シ", meaning: "diri", level: "Pemula"),
					KanjiModel(kanji: "身", kunyomi: "み", onyomi: "シン", meaning: "seseorang, orang", level: "Pemula"),
					KanjiModel(kanji: "意", kunyomi: "-", onyomi: "イ", meaning: "perasaan; pikiran, artinya", level: "Pemula"),
					KanjiModel(kanji: "見", kunyomi: "み.る、 み.える", onyomi: "ケン", meaning: "lihat, harapan, peluang", level: "Pemula"),
					KanjiModel(kanji: "稿", kunyomi: "わら、 したがき", onyomi: "コウ", meaning: "draft, copy, manuskrip", level: "Mahir"),
					KanjiModel(kanji: "変", kunyomi: "か.わる", onyomi: "ヘン", meaning: "tidak biasa, perubahan", level: "Lanjut"),
					KanjiModel(kanji: "分", kunyomi: "わ.ける、 わ.け", onyomi: "ブン、 フン、 ブ", meaning: "bagian, berbagi, menit", level: "Pemula"),
					KanjiModel(kanji: "起", kunyomi: "お.きる、 お.こる", onyomi: "キ", meaning: "Bangui", level: "Pemula"),
					KanjiModel(kanji: "用", kunyomi: "もち.いる", onyomi: "ヨウ", meaning: "memanfaatkan, bisnis", level: "Pemula"),
					KanjiModel(kanji: "法", kunyomi: "のり", onyomi: "ホウ、 ハッ", meaning: "metode, hukum", level: "Lanjut"),
					KanjiModel(kanji: "数", kunyomi: "かず、 かぞ.える", onyomi: "スウ、 ス", meaning: "nomor, kekuatan", level: "Lanjut"),
					KanjiModel(kanji: "字", kunyomi: "あざ、 あざな", onyomi: "ジ", meaning: "karakter, huruf", level: "Pemula"),
					KanjiModel(kanji: "述", kunyomi: "の.べる", onyomi: "ジュツ", meaning: "menyebutkan, menyatakan", level: "Mahir"),
					KanjiModel(kanji: "大", kunyomi: "おお-、 おお.きい", onyomi: "ダイ、 タイ", meaning: "besar", level: "Pemula"),
					KanjiModel(kanji: "反", kunyomi: "そ.る、 そ.らす", onyomi: "ハン、 ホン", meaning: "anti", level: "Lanjut"),
					KanjiModel(kanji: "響", kunyomi: "ひび.く", onyomi: "キョウ", meaning: "gema, suara, bergema", level: "Mahir"),
					KanjiModel(kanji: "呼", kunyomi: "よ.ぶ", onyomi: "コ", meaning: "memanggil, mengundang", level: "Lanjut"),
					KanjiModel(kanji: "賛", kunyomi: "たす.ける", onyomi: "サン", meaning: "menyetujui, memuji", level: "Lanjut"),
					KanjiModel(kanji: "否", kunyomi: "いな、 いや", onyomi: "ヒ", meaning: "meniadakan, tidak", level: "Lanjut"),
					KanjiModel(kanji: "両", kunyomi: "てる、 ふたつ", onyomi: "リョウ", meaning: "keduanya, koin Jepang kuno", level: "Lanjut"),
					KanjiModel(kanji: "論", kunyomi: "あげつら.う", onyomi: "ロン", meaning: "argumen, wacana", level: "Lanjut"),
					KanjiModel(kanji: "多", kunyomi: "おお.い", onyomi: "タ", meaning: "banyak, sering", level: "Pemula"),
					KanjiModel(kanji: "寄", kunyomi: "よ.る、 よ.り", onyomi: "キ", meaning: "mendekat, mampir", level: "Lanjut")
				],
				quiz: [
					QuestionModel(questionTitle: "Apa Makna Kanji", answers: ["Nanti", "Kemarin", "Sekarang", "Besok"], correctAnswerIndex: 2, isKanji: true, kanjitext: "今"),
					QuestionModel(questionTitle: "Bagaimana cara membaca kunyomi kanji", answers: ["み", "り", "お", "ぶ"], correctAnswerIndex: 0, isKanji: true, kanjitext: "身"),
					QuestionModel(questionTitle: "Apa Makna Kanji", answers: ["Kecil", "Besar", "Kiri", "Kanan"], correctAnswerIndex: 1, isKanji: true, kanjitext: "大"),
					QuestionModel(questionTitle: "Apakah arti kanji ini", answers: ["Istirahat", "Buku", "Diri", "Orang"], correctAnswerIndex: 2, isKanji: true, kanjitext: "自"),
					QuestionModel(questionTitle: "Bagaimana cara membaca kunyomi kanji", answers: ["まさ", "あげ", "ふた", "あざ"], correctAnswerIndex: 3, isKanji: true, kanjitext: "字"),
					QuestionModel(questionTitle: "Siapakah yang terpilih memenangkan penghargaan Sawamura", answers: ["沢村賞", "賛否両論", "山本由伸投手", "起用法", "時代"], correctAnswerIndex: 2, isKanji: false, kanjitext: ""),
					QuestionModel(questionTitle: "Apa Makna Kanji", answers: ["Hewan", "Orang", "Benda", "Kendaraan"], correctAnswerIndex: 1, isKanji: true, kanjitext: "身"),
					QuestionModel(questionTitle: "Bagaimana cara membaca kunyomi kanji", answers: ["まさ", "せる", "ふた", "おおき"], correctAnswerIndex: 3, isKanji: true, kanjitext: "大"),
					QuestionModel(questionTitle: "Media sosial apakah yang disebutkan dalam bacaan?", answers: ["Facebook", "Twitter", "TikTok", "Instagram"], correctAnswerIndex: 1, isKanji: false, kanjitext: ""),
					QuestionModel(questionTitle: "Apa Makna Kanji", answers: ["Huruf", "Langit", "Bumi", "Buku"], correctAnswerIndex: 0, isKanji: true, kanjitext: "字"),
				],
				quizscore: 0),
			ArticleModel(
				image: "camera",
				titleJP: "光で写す",
				titleID: "Foto dengan cahaya",
				level: "Pemula",
				topic: "Teknologi",
				articleJP: "今日のブラックボックスは、カメラ。レンズから取り込まれた光は、さまざまな部品を通って映像になります。どのように光を映像に変えているのか、詳しく見ていきましょう。まず、レンズが目の前の風景の光をカメラの中に取り込み、イメージセンサのもとへ届けます。このイメージセンサには、なんと1000万以上の小さなセンサが規則正しく並んでいます。それぞれが、光の三原色、赤・青・緑の光の強さを読み取り、電気信号に変えることができます。 その電気信号が、画像処理エンジンと呼ばれるコンピュータに送られると、三色の光を認識します。画像処理エンジンは、この三色の光を組み合わせることで、フルカラーの映像を作っています。その映像は液晶画面に伝わり、表示されます。その映像を見て、私たちはシャッターボタンを押し、メモリカードに写真として記録しているのです",
				articleID: "Kotak hitam hari ini adalah kamera. Cahaya yang ditangkap dari lensa melewati berbagai bagian dan menjadi sebuah gambar. Mari kita lihat lebih dekat bagaimana cahaya diubah menjadi video. Pertama, lensa menangkap cahaya lanskap di depan Anda ke dalam kamera dan mengirimkannya ke sensor gambar. Sensor gambar ini memiliki lebih dari 10 juta sensor kecil yang berbaris secara teratur. Masing-masing dapat membaca tiga warna utama cahaya, intensitas cahaya merah, biru, dan hijau, dan mengubahnya menjadi sinyal listrik. Ketika sinyal listrik dikirim ke komputer yang disebut mesin pengolah gambar, ia mengenali tiga warna cahaya. Mesin pengolah gambar menciptakan gambar penuh warna dengan menggabungkan ketiga warna cahaya ini. Gambar ditransmisikan ke layar LCD dan ditampilkan. Setelah melihat video, kami menekan tombol rana dan merekamnya sebagai foto di kartu memori.",
				articleSource: "https://www2.nhk.or.jp/school/movie/bangumi.cgi?das_id=D0005250016_00000",
				isSeen: true,
				isQuizTaken: false,
				kanji: [
					KanjiModel(kanji: "今", kunyomi: "いま", onyomi: "コン、 キン", meaning: "sekarang", level: "Pemula"),
					KanjiModel(kanji: "日", kunyomi: "ひ、 び、 か", onyomi: "ニチ、 ジツ", meaning: "hari, matahari", level: "Pemula"),
					KanjiModel(kanji: "取", kunyomi: "と.る、 と.り", onyomi: "シュ", meaning: "ambil", level: "Lanjut"),
					KanjiModel(kanji: "込", kunyomi: "こ.む、 こ.む", onyomi: "-", meaning: "ramai, campuran,", level: "Lanjut"),
					KanjiModel(kanji: "光", kunyomi: "ひか.る", onyomi: "コウ", meaning: "sinar, cahaya", level: "Lanjut"),
					KanjiModel(kanji: "品", kunyomi: "しな", onyomi: "ヒン、 ホン", meaning: "barang, perbaikan", level: "Pemula"),
					KanjiModel(kanji: "通", kunyomi: "とお.る", onyomi: "ツウ、ツ", meaning: "lalu lintas", level: "Pemula"),
					KanjiModel(kanji: "映", kunyomi: "うつ.る", onyomi: "エイ", meaning: "mencerminkan", level: "Pemula"),
					KanjiModel(kanji: "像", kunyomi: "-", onyomi: "ゾウ", meaning: "patung", level: "Mahir"),
					KanjiModel(kanji: "変", kunyomi: "か.わる", onyomi: "ヘン", meaning: "tidak biasa", level: "Lanjut"),
					KanjiModel(kanji: "詳", kunyomi: "くわ.しい", onyomi: "ショウ", meaning: "detail", level: "Mahir"),
					KanjiModel(kanji: "見", kunyomi: "み.る", onyomi: "ケン", meaning: "lihat", level: "Pemula"),
					KanjiModel(kanji: "目", kunyomi: "め", onyomi: "モク、 ボク", meaning: "mata", level: "Pemula"),
					KanjiModel(kanji: "前", kunyomi: "まえ、-まえ", onyomi: "ゼン", meaning: "di depan, sebelum", level: "Pemula"),
					KanjiModel(kanji: "風", kunyomi: "かぜ、かざ-", onyomi: "フウ、フ", meaning: "angin, udara, gaya, cara", level: "Pemula"),
					KanjiModel(kanji: "景", kunyomi: "-", onyomi: "ケイ", meaning: "pemandangan", level: "Lanjut"),
					KanjiModel(kanji: "中", kunyomi: "なか、うち", onyomi: "チュウ", meaning: "di dalam, ditengah", level: "Pemula"),
					KanjiModel(kanji: "届", kunyomi: "とど.ける、-とど.け", onyomi: "カイ", meaning: "mengantarkan, mencapai", level: "Mahir"),
					KanjiModel(kanji: "万", kunyomi: "よろず", onyomi: "マン、バン", meaning: "sepuluh ribu, 10.000", level: "Pemula"),
					KanjiModel(kanji: "以", kunyomi: "もっ.て", onyomi: "イ", meaning: "dengan cara, karena", level: "Pemula"),
					KanjiModel(kanji: "上", kunyomi: "うえ、-うえ", onyomi: "ジョウ、ショウ、シャン", meaning: "atas, diatas", level: "Pemula"),
					KanjiModel(kanji: "小", kunyomi: "ちい.さい、こ-", onyomi: "ショウ", meaning: "kecil", level: "Pemula"),
					KanjiModel(kanji: "規", kunyomi: "-", onyomi: "キ", meaning: "standar, ukuran", level: "Lanjut"),
					KanjiModel(kanji: "則", kunyomi: "のっと.る、のり", onyomi: "ソク", meaning: "aturan, hukum", level: "Mahir"),
					KanjiModel(kanji: "正", kunyomi: "ただ.しい、ただ.す", onyomi: "セイ、ショウ", meaning: "benar, adil", level: "Pemula"),
					KanjiModel(kanji: "並", kunyomi: "な.み、なみ", onyomi: "ヘイ、ホウ", meaning: "baris, dan, selain itu", level: "Mahir"),
					KanjiModel(kanji: "三", kunyomi: "み、み.つ", onyomi: "サン、ゾウ", meaning: "tiga", level: "Pemula"),
					KanjiModel(kanji: "原", kunyomi: "はら", onyomi: "ゲン", meaning: "padang rumput", level: "Lanjut"),
					KanjiModel(kanji: "色", kunyomi: "いろ", onyomi: "ショク、シキ", meaning: "warna", level: "Pemula"),
					KanjiModel(kanji: "赤", kunyomi: "あか、あか-", onyomi: "セキ、シャク", meaning: "merah", level: "Pemula"),
					KanjiModel(kanji: "青", kunyomi: "あお、あお-、あお.い", onyomi: "セイ、ショウ", meaning: "biru, hijau", level: "Pemula"),
					KanjiModel(kanji: "緑", kunyomi: "みどり", onyomi: "リョク、ロク", meaning: "hijau", level: "Mahir"),
					KanjiModel(kanji: "強", kunyomi: "つよ.い、つよ.まる", onyomi: "キョウ、ゴウ", meaning: "kuat", level: "Pemula"),
					KanjiModel(kanji: "読", kunyomi: "よ.む、-よ.み", onyomi: "ドク、トク、トウ", meaning: "baca", level: "Pemula"),
					KanjiModel(kanji: "電", kunyomi: "-", onyomi: "デン", meaning: "listrik", level: "Pemula"),
					KanjiModel(kanji: "気", kunyomi: "き", onyomi: "キ、ケ", meaning: "semangat, pikiran, udara", level: "Pemula"),
					KanjiModel(kanji: "信", kunyomi: "-", onyomi: "シン", meaning: "iman, kebenaran", level: "Lanjut"),
					KanjiModel(kanji: "号", kunyomi: "さけ.ぶ、よびな", onyomi: "ゴウ", meaning: "nama panggilan, nomor", level: "Lanjut"),
					KanjiModel(kanji: "画", kunyomi: "えが.く、かく.する", onyomi: "ガ、カク、エ、カイ", meaning: "sapuan kuas, gambar", level: "Pemula"),
					KanjiModel(kanji: "処", kunyomi: "ところ、-こ、お.る", onyomi: "ショ", meaning: "membuang, mengelola", level: "Lanjut"),
					KanjiModel(kanji: "理", kunyomi: "ことわり", onyomi: "リ", meaning: "logika, pengaturan, alasan", level: "Pemula"),
					KanjiModel(kanji: "呼", kunyomi: "よ.ぶ", onyomi: "コ", meaning: "memanggil, mengundang", level: "Lanjut"),
					KanjiModel(kanji: "送", kunyomi: "おく.る", onyomi: "ソウ", meaning: "mengantar, mengirim", level: "Pemula"),
					KanjiModel(kanji: "認", kunyomi: "みと.める、したた.める", onyomi: "ニン", meaning: "mengakui, menyaksikan", level: "Lanjut"),
					KanjiModel(kanji: "識", kunyomi: "し.る、しる.す", onyomi: "シキ", meaning: "membedakan, tahu, menulis", level: "Lanjut"),
					KanjiModel(kanji: "組", kunyomi: "く.む、くみ、-ぐみ", onyomi: "ソ", meaning: "asosiasi, kepang, anyaman", level: "Lanjut"),
					KanjiModel(kanji: "合", kunyomi: "あ.う、-あ.う", onyomi: "ゴウ、ガッ、カッ", meaning: "cocok, bergabung", level: "Lanjut"),
					KanjiModel(kanji: "作", kunyomi: "つく.る、つく.り、-づく.り", onyomi: "サク、サ", meaning: "membuat, produksi", level: "Pemula"),
					KanjiModel(kanji: "液", kunyomi: "-", onyomi: "エキ", meaning: "cairan, jus", level: "Mahir"),
					KanjiModel(kanji: "晶", kunyomi: "-", onyomi: "ショウ", meaning: "berkilau, jernih, kristal", level: "Mahir"),
					KanjiModel(kanji: "面", kunyomi: "おも、おもて、つら", onyomi: "メン、ベン", meaning: "topeng, wajah, fitur", level: "Lanjut"),
					KanjiModel(kanji: "伝", kunyomi: "つた.わる、つた.える", onyomi: "デン、テン", meaning: "mengirimkan, ikut", level: "Lanjut"),
					KanjiModel(kanji: "表", kunyomi: "おもて、-おもて", onyomi: "ヒョウ", meaning: "permukaan, tabel", level: "Lanjut"),
					KanjiModel(kanji: "示", kunyomi: "しめ.す", onyomi: "ジ、シ", meaning: "menunjukkan, mengungkapkan", level: "Lanjut"),
					KanjiModel(kanji: "私", kunyomi: "わたくし、わたし", onyomi: "シ", meaning: "pribadi, saya", level: "Pemula"),
					KanjiModel(kanji: "押", kunyomi: "お.す、お.し-", onyomi: "オウ", meaning: "dorong, hentikan", level: "Lanjut"),
					KanjiModel(kanji: "写", kunyomi: "うつ.す、うつ.る", onyomi: "シャ、ジャ", meaning: "salin, difoto, deskripsikan", level: "Pemula"),
					KanjiModel(kanji: "真", kunyomi: "ま、ま-、まこと", onyomi: "シン", meaning: "benar, kenyataan", level: "Lanjut"),
					KanjiModel(kanji: "録", kunyomi: "しる.す、と.る", onyomi: "ロク", meaning: "catatan, rekam", level: "Mahir"),
				],
				quiz: [
					QuestionModel(questionTitle: "Apa Makna Kanji", answers: ["Hidung", "Pipi", "Telinga", "Mata"], correctAnswerIndex: 3, isKanji: true, kanjitext: "目"),
					QuestionModel(questionTitle: "Bagaimana cara membaca kunyomi kanji", answers: ["いま", "しな", "いろ", "はら"], correctAnswerIndex: 2, isKanji: true, kanjitext: "色"),
					QuestionModel(questionTitle: "Apa Makna Kanji", answers: ["20.000", "10.000", "40.000", "30.000"], correctAnswerIndex: 1, isKanji: true, kanjitext: "万"),
					QuestionModel(questionTitle: "Bagaimana cara membaca kunyomi kanji", answers: ["よびな", "ところ", "つまび", "よろず"], correctAnswerIndex: 3, isKanji: true, kanjitext: "万"),
					QuestionModel(questionTitle: "Berapa jumlah sensor kecil yang menyusun sensor gambar pada kamera", answers: [">20jt", "<20jt", "<10jt", ">10jt"], correctAnswerIndex: 3, isKanji: false, kanjitext: ""),
					QuestionModel(questionTitle: "Apa Makna Kanji", answers: ["Manga", "Artikel", "Artikel", "Gambar"], correctAnswerIndex: 3, isKanji: true, kanjitext: "画"),
					QuestionModel(questionTitle: "Bagaimana cara membaca kunyomi kanji", answers: ["み", "ま", "き", "は"], correctAnswerIndex: 0, isKanji: true, kanjitext: "三"),
					QuestionModel(questionTitle: "Apa Makna Kanji", answers: ["Sedang", "Besar", "Jumbo", "Kecil"], correctAnswerIndex: 3, isKanji: true, kanjitext: "小"),
					QuestionModel(questionTitle: "Bagaimana cara membaca kunyomi kanji", answers: ["よびな", "ところ", "おくる", "つまび"], correctAnswerIndex: 2, isKanji: true, kanjitext: "送"),
					QuestionModel(questionTitle: "Ke bagian mana foto disimpan oleh kamera", answers: ["LCD", "Kartu Memori", "Harddisk", "USB"], correctAnswerIndex: 1, isKanji: false, kanjitext: "")
				],
				quizscore: 0),
			ArticleModel(
				image: "burger",
				titleJP: "米マクドナルドが“代替肉”バーガー 販売へ",
				titleID: "McDonald's akan menjual burger \"daging alternatif\"",
				level: "Pemula",
				topic: "Kuliner",
				articleJP: "マクドナルドは２６日、カナダの２８店舗で新しいハンバーガー「Ｐ．Ｌ．Ｔ」を今月末から１２月下旬まで、試験的に販売すると発表しました。「Ｐ．Ｌ．Ｔ」は植物、レタス、トマトの略でその名の通り、肉を全く使わずにエンドウ豆のたんぱく質など植物性の原料で味やにおい、食感を再現した「代替肉」のバーガーです。アメリカの食品会社「ビヨンド・ミート」が開発した「代替肉」を使っていて、バーガーは１個当たり４６０キロカロリーで、価格は６．４９カナダドル、日本円でおよそ５３０円です。",
				articleID: "McDonald's mengumumkan pada tanggal 26 bahwa mereka akan menjual hamburger \"PLT\" baru di 28 toko di Kanada dengan basis percobaan dari akhir bulan ini hingga akhir Desember. \"PLT\" adalah singkatan dari tumbuhan, selada, dan tomat, dan seperti namanya, itu adalah \"daging alternatif\" yang mereproduksi rasa, bau, dan tekstur bahan nabati seperti protein kacang polong tanpa menggunakan daging sama sekali. adalah burger dari. \nMenggunakan \"daging alternatif\" yang dikembangkan oleh perusahaan makanan Amerika \"Beyond Meat\", setiap burger memiliki 460 kilokalori, dan harganya 6,49 dolar Kanada, sekitar 530 yen dalam yen Jepang.",
				articleSource: "http://easyjapanese.net/detail/cc0e2186b127ce29873d2c1489147a63?hl=en-US",
				isSeen: false,
				isQuizTaken: false,
				kanji: [
					KanjiModel(kanji: "日", kunyomi: "ひ、 -び、 -か", onyomi: "ニチ、 ジツ", meaning: "hari, matahari, Jepang", level: "Pemula"),
					KanjiModel(kanji: "店", kunyomi: "みせ、 たな", onyomi: "テン", meaning: "toko peralatan", level: "Pemula"),
					KanjiModel(kanji: "舗", kunyomi: "-", onyomi: "ホ", meaning: "toko, paving", level: "Mahir"),
					KanjiModel(kanji: "新", kunyomi: "あたら.しい、 あら.た", onyomi: "シン", meaning: "baru", level: "Lanjut"),
					KanjiModel(kanji: "今", kunyomi: "いま", onyomi: "コン、 キン", meaning: "sekarang", level: "Pemula"),
					KanjiModel(kanji: "月", kunyomi: "つき", onyomi: "ゲツ、 ガツ", meaning: "bulan", level: "Pemula"),
					KanjiModel(kanji: "末", kunyomi: "すえ、 うら、 うれ", onyomi: "マツ、 バツ", meaning: "akhir, tutup, tip, bedak", level: "Lanjut"),
					KanjiModel(kanji: "下", kunyomi: "した、 しも、 もと、 さ.げる", onyomi: "カ、 ゲ", meaning: "bawah, turun, memberi, rendah, inferior", level: "Pemula"),
					KanjiModel(kanji: "旬", kunyomi: "-", onyomi: "ジュン、 シュン", meaning: "musim (misalnya buah, ikan), periode sepuluh hari (dalam sebulan)", level: "Mahir"),
					KanjiModel(kanji: "試", kunyomi: "こころ.みる、 ため.す", onyomi: "シ", meaning: "tes, coba, percobaan, cobaan", level: "Pemula"),
					KanjiModel(kanji: "験", kunyomi: "あかし、 しるし、 ため.す、 ためし", onyomi: "ケン、 ゲン", meaning: "verifikasi, efek, pengujian", level: "Pemula"),
					KanjiModel(kanji: "的", kunyomi: "まと", onyomi: "テキ", meaning: "objek, akhiran kata sifat", level: "Pemula"),
					KanjiModel(kanji: "販", kunyomi: "-", onyomi: "ハン", meaning: "pemasaran, penjualan, perdagangan", level: "Mahir"),
					KanjiModel(kanji: "売", kunyomi: "う.る、 う.れる", onyomi: "バイ", meaning: "jual", level: "Pemula"),
					KanjiModel(kanji: "発", kunyomi: "た.つ、 あば.く", onyomi: "ハツ、 ホツ", meaning: "keberangkatan, pelepasan", level: "Pemula"),
					KanjiModel(kanji: "表", kunyomi: "おもて、 -おもて", onyomi: "ヒョウ", meaning: "permukaan, tabel, bagan, diagram", level: "Lanjut"),
					KanjiModel(kanji: "植", kunyomi: "う.える、 う.わる", onyomi: "ショク", meaning: "tanaman; vegetasi", level: "Mahir"),
					KanjiModel(kanji: "物", kunyomi: "もの、 もの-", onyomi: "ブツ、 モツ", meaning: "hal, objek, materi", level: "Pemula"),
					KanjiModel(kanji: "略", kunyomi: "ほぼ、 はぶ.く", onyomi: "リャク", meaning: "singkatan, kelalaian", level: "Mahir"),
					KanjiModel(kanji: "名", kunyomi: "な、 -な", onyomi: "メイ、 ミョウ", meaning: "nama, dicatat, dibedakan, reputasi", level: "Pemula"),
					KanjiModel(kanji: "通", kunyomi: "とお.る、 とお.り", onyomi: "ツウ、 ツ", meaning: "lalu lintas, melewati, jalan", level: "Pemula"),
					KanjiModel(kanji: "肉", kunyomi: "しし", onyomi: "ニク", meaning: "daging", level: "Pemula"),
					KanjiModel(kanji: "全", kunyomi: "まった.く、 すべ.て", onyomi: "ゼン", meaning: "seluruh, seluruh, semua, lengkap, memenuhi", level: "Lanjut"),
					KanjiModel(kanji: "使", kunyomi: "つか.う、 つか.い", onyomi: "シ", meaning: "gunakan, kirim misi, perintah", level: "Pemula"),
					KanjiModel(kanji: "豆", kunyomi: "まめ、 まめ-", onyomi: "トウ、 ズ", meaning: "kacang, kacang polong, cebol", level: "Mahir"),
					KanjiModel(kanji: "質", kunyomi: "たち、 ただ.す、 もと、 わりふ", onyomi: "シツ、 シチ、 チ", meaning: "substansi, kualitas, materi, temperamen", level: "Pemula"),
					KanjiModel(kanji: "性", kunyomi: "さが", onyomi: "セイ、 ショウ", meaning: "jenis kelamin, sifat", level: "Lanjut"),
					KanjiModel(kanji: "原", kunyomi: "はら", onyomi: "ゲン", meaning: "padang rumput, asli, primitif, bidang,", level: "Lanjut"),
					KanjiModel(kanji: "料", kunyomi: "-", onyomi: "リョウ", meaning: "biaya, bahan", level: "Lanjut"),
					KanjiModel(kanji: "味", kunyomi: "あじ、 あじ.わう", onyomi: "ショク、 ジキ", meaning: "rasa", level: "Pemula"),
					KanjiModel(kanji: "食", kunyomi: "く.う、 く.らう", onyomi: "イン", meaning: "makan, makanan", level: "Pemula"),
					KanjiModel(kanji: "感", kunyomi: "-", onyomi: "カン", meaning: "emosi, perasaan, sensasi", level: "Lanjut"),
					KanjiModel(kanji: "再", kunyomi: "ふたた.び", onyomi: "サイ、 サ", meaning: "lagi, dua kali, kedua kalinya", level: "Mahir"),
					KanjiModel(kanji: "現", kunyomi: "あらわ.れる、 あらわ.す", onyomi: "ゲン", meaning: "present, existing, actual", level: "Lanjut"),
					KanjiModel(kanji: "代", kunyomi: "か.わる、 かわ.る", onyomi: "ダイ、 タイ", meaning: "mengganti, mengubah, mengonversi,", level: "Pemula"),
					KanjiModel(kanji: "替", kunyomi: "か.える、 か.え-、 か.わる", onyomi: "タイ", meaning: "pertukaran, cadangan, pengganti, per-", level: "Mahir"),
					KanjiModel(kanji: "品", kunyomi: "しな", onyomi: "ヒン、 ホン", meaning: "barang, perbaikan, martabat", level: "Pemula"),
					KanjiModel(kanji: "会", kunyomi: "あ.う、 あ.わせる、 あつ.まる", onyomi: "カイ、 エ", meaning: "pertemuan, bertemu, pesta, ", level: "Pemula"),
					KanjiModel(kanji: "社", kunyomi: "やしろ", onyomi: "シャ", meaning: "perusahaan, firma, kantor, asosiasi, kuil", level: "Pemula"),
					KanjiModel(kanji: "開", kunyomi: "ひら.く、 ひら.き", onyomi: "カイ", meaning: "buka, buka segel", level: "Pemula"),
					KanjiModel(kanji: "個", kunyomi: "-", onyomi: "コ、 カ", meaning: "individu, counter untuk artikel", level: "Mahir"),
					KanjiModel(kanji: "当", kunyomi: "あ.たる、 あ.たり", onyomi: "トウ", meaning: "pukul, benar, tepat, dirinya sendiri", level: "Lanjut"),
					KanjiModel(kanji: "価", kunyomi: "あたい", onyomi: "カ、 ケ", meaning: "nilai, harga", level: "Mahir"),
					KanjiModel(kanji: "格", kunyomi: "-", onyomi: "カク、 コウ、 キャク、 ゴウ", meaning: "status, pangkat, kapasitas", level: "Lanjut"),
					KanjiModel(kanji: "本", kunyomi: "もと", onyomi: "ホン", meaning: "buku, sekarang, utama, asal, benar,", level: "Pemula"),
					KanjiModel(kanji: "円", kunyomi: "まる.い、 まる", onyomi: "エン", meaning: "lingkaran, yen, bulat", level: "Pemula"),
				],
				quiz: [
					QuestionModel(questionTitle: "Apakah arti kanji berikut ini?", answers: ["Lingkaran", "Kotak", "Segitiga", "Silang"], correctAnswerIndex: 0, isKanji: true, kanjitext: "円"),
					QuestionModel(questionTitle: "Bagaimana cara membaca kunyomi kanji ini?", answers: ["もと", "みせ", "しな", "もの"], correctAnswerIndex: 1, isKanji: true, kanjitext: "店"),
					QuestionModel(questionTitle: "Apakah arti kanji berikut ini?", answers: ["Olahraga", "Tidur", "Makan", "Minum"], correctAnswerIndex: 2, isKanji: true, kanjitext: "食"),
					QuestionModel(questionTitle: "Bagaimana cara membaca kunyomi kanji ini?", answers: ["しな", "もの", "みせ", "もと"], correctAnswerIndex: 3, isKanji: true, kanjitext: "本"),
					QuestionModel(questionTitle: "Berapa kilokalori yang dimiliki setiap burger?", answers: ["450", "460", "470", "480"], correctAnswerIndex: 1, isKanji: false, kanjitext: ""),
					QuestionModel(questionTitle: "Apakah arti kanji berikut ini?", answers: ["Bulan", "Matahari", "Bintang", "Planet"], correctAnswerIndex: 0, isKanji: true, kanjitext: "月"),
					QuestionModel(questionTitle: "Bagaimana cara membaca kunyomi kanji ini?", answers: ["もと", "しな", "もの", "まと"], correctAnswerIndex: 3, isKanji: true, kanjitext: "的"),
					QuestionModel(questionTitle: "Apakah arti kanji berikut ini?", answers: ["Sayur", "Daging", "Susu", "Buah"], correctAnswerIndex: 1, isKanji: true, kanjitext: "肉"),
					QuestionModel(questionTitle: "Bagaimana cara membaca kunyomi kanji ini?", answers: ["まと", "もと", "う.る", "しな"], correctAnswerIndex: 2, isKanji: true, kanjitext: "売"),
					QuestionModel(questionTitle: "Kapan masa penjualan burger daging alternatif berakhir? ", answers: ["Desember", "November", "Oktober", "September"], correctAnswerIndex: 0, isKanji: false, kanjitext: ""),
				],
				quizscore: 0),
		]
		article.append(contentsOf: newArticles)
	}
	
}
